# Generated by Django 4.1.7 on 2023-03-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0002_person_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('request_type', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=4)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(help_text='Enter your email', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(help_text='Enter your first name', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(help_text='Enter your last name', max_length=100),
        ),
    ]
