# Generated by Django 4.1.7 on 2023-03-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0003_logs_alter_person_email_alter_person_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
