# Generated by Django 4.1.7 on 2023-03-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0004_logs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='data',
        ),
    ]
