# Generated by Django 4.1.7 on 2023-03-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0006_logs_cookies_logs_headers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='cookies',
        ),
    ]
