# Generated by Django 4.1.7 on 2023-03-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0007_remove_logs_cookies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='headers',
        ),
        migrations.AddField(
            model_name='logs',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
