# Generated by Django 4.1.7 on 2023-03-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0009_rename_request_type_logs_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='data',
            new_name='get_data',
        ),
        migrations.AddField(
            model_name='logs',
            name='post_data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
