# Generated by Django 4.1.7 on 2023-03-28 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0011_rename_get_data_logs_data_remove_logs_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math_app.person'),
        ),
    ]
