# Generated by Django 4.1.7 on 2023-03-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0012_alter_logs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
