# Generated by Django 4.1.7 on 2023-03-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_client_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.city'),
        ),
    ]
